package vue;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

import model.FormulaireMedecin;

public class Administrateur1 extends javax.swing.JFrame{
	/*
	 * To change this license header, choose License Headers in Project Properties.
	 * To change this template file, choose Tools | Templates
	 * and open the template in the editor.
	 */
	
	

	    /**
	     * Creates new form Administrateur
	     */
	    public Administrateur1() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jPanel2 = new javax.swing.JPanel();
	        ajouter = new javax.swing.JButton();
	        modifier = new javax.swing.JButton();
	        lister = new javax.swing.JButton();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        rechercher = new javax.swing.JButton();
	        champsrechercher = new javax.swing.JTextField();
	        jPanel3 = new javax.swing.JPanel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        medicament = new javax.swing.JButton();
	        jLabel1 = new javax.swing.JLabel();
	        fermer = new javax.swing.JButton();
	        labelbienvenu = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setPreferredSize(new java.awt.Dimension(950, 735));
	        setBounds(150, 0, 0, 0);
	        
	        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

	        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
	        jPanel2.setPreferredSize(new java.awt.Dimension(980, 800));

	        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/ajouter.png"))); // NOI18N
	        ajouter.setText("Ajouter");
	        ajouter.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {

	            
	            AjouterMedecinAdmin ama = new AjouterMedecinAdmin();
	            ama.setVisible(true);
	              
	            }
	        });
	        rechercher.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
                  
	            
	            	String txt=champsrechercher.getText();
	            	
	            	int pos=search(txt, tableau,4);
	            	if (pos<0){
	            	 JOptionPane.showMessageDialog(Administrateur1.this, "Aucun élément trouvé");
	            	 
	            	}
	            	else{
	            		//JOptionPane.showMessageDialog(Administrateur1.this, "Position: " + pos);            		
	            		tableau.setRowSelectionInterval(pos, pos);
	            		tableau.scrollRectToVisible(new java.awt.Rectangle(tableau.getCellRect(pos, 0, true)));
	            	}
	              
	            }
	        });

	        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/modifier.png"))); // NOI18N
	        modifier.setText("Modifier");
	        modifier.setName("modifier"); // NOI18N
	        modifier.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	
	            	id_fiche=Integer.parseInt(JOptionPane.showInputDialog(null,"Entrez le numero du patient"));
	        		FormulaireMedecin fm=new FormulaireMedecin();
	        		String [] tab= fm.modifier(id_fiche);
	        		System.out.println("bon 1"+tab[0]);
	        		
	            	ModifierMedecinAdmin mod= new ModifierMedecinAdmin(tab);
	            	System.out.println("bon 2");
	        		mod.setVisible(true);
	        		 
	            }
	        });

	        lister.setText("Param Secrétaire");
	        lister.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	dispose();
	            	Administrateur2 a=new Administrateur2();
	            	a.setVisible(true);
	        		 
	            }
	        });

	        FormulaireMedecin fr=new FormulaireMedecin();
			data=fr.MedecinRecupAdmin();
			
			 
	        String [] titretab={ "N° Medecin", "Nom", "Prenom", "Specialite", "Login","Mot de passe"};
	        tableau =new JTable(data,titretab);


	        //lister.setText("Lister");

	    /**    jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null},
	                {null, null, null, null, null, null}
	            },
	            new String [] {
	                "Identifiant ", "Nom", "Prénom", "Specialité", "Login ", "Mot de passe"
	            }
	        ) {
	            boolean[] canEdit = new boolean [] {
	                false, false, false, false, false, false
	            };

	            public boolean isCellEditable(int rowIndex, int columnIndex) {
	                return canEdit [columnIndex];
	            }
	        });*/
	        jScrollPane1.setViewportView(tableau);

	        rechercher.setText("Search");

	        champsrechercher.setText("Entrer le login");
	        champsrechercher.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                champsrechercherActionPerformed(evt);
	            }
	        });

	        jLabel2.setText("System de gestion Medical TEAM 4 2016-2017");

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addGap(359, 359, 359)
	                .addComponent(jLabel2)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                .addContainerGap(18, Short.MAX_VALUE)
	                .addComponent(jLabel2)
	                .addContainerGap())
	        );

	        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
	        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
	        jLabel3.setText("LISTE DES MEDECINS");

	        medicament.setText("Param Medicament");
	        medicament.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                Medicament medoc= new Medicament();
	                medoc.setVisible(true);
	            }
	        });

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel2Layout.createSequentialGroup()
	                                .addGap(270, 270, 270)
	                                .addComponent(jLabel3)
	                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                            .addGroup(jPanel2Layout.createSequentialGroup()
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(lister, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(champsrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                .addComponent(rechercher)
	                                .addGap(18, 18, 18))))
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
	                                .addComponent(medicament)
	                                .addGap(9, 9, 9)))
	                        .addContainerGap(25, Short.MAX_VALUE))))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(119, 119, 119)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(champsrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(33, 33, 33)
	                .addComponent(jLabel3)
	                .addGap(18, 18, 18)
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(34, 34, 34)
	                .addComponent(medicament, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(89, 89, 89)
	                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(194, Short.MAX_VALUE))
	        );

	        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/logo.jpg"))); // NOI18N
	        jLabel1.setText("jLabel1");

	        fermer.setBackground(new java.awt.Color(255, 51, 0));
	        fermer.setText("Deconnexion");
	        fermer.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	Acceuil a = new Acceuil();
	            	dispose();
	            	a.setVisible(true);
	            }
	        });

	     //  labelbienvenu.setText("BIENVENUE .........................");

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(labelbienvenu)
	                .addGap(258, 258, 258)
	                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap())
	            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGap(25, 25, 25)
	                        .addComponent(jLabel1)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(fermer)
	                            .addComponent(labelbienvenu))
	                        .addGap(2, 2, 2)))
	                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(0, 0, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>                        
	    public int search(String txt, JTable tableau, int indexChamp){
			TableModel model = tableau.getModel();
			Object[][] tuples = new Object[model.getRowCount()][model.getColumnCount()];
			for(int i=0; i < tuples.length; i++)
				for(int j=0; j < tuples[i].length; j++)
					tuples[i][j] = model.getValueAt(i, j);
	    		
			return search(txt, tuples, indexChamp);
		}
		
		public int search(String txt, Object[][] tuples, int indexChamp){
			for(int i=0; i < tuples.length; i++)
				if(search(txt, tuples[i], indexChamp))
					return i;
			return -1;
		}

		public boolean search(String txt, Object[] tuple, int indexChamp){
			try{
				String val = (String) tuple[indexChamp];
				return (val.compareToIgnoreCase(txt) == 0);
			}	
			catch (Exception e){
				return false;
			}}
	    /**
	     * @param args the command line arguments
	     */
	    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    }                                        

	    private void champsrechercherActionPerformed(java.awt.event.ActionEvent evt) {                                                 
	        // TODO add your handling code here:
	    }                                                

	    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {                                       
	        // TODO add your handling code here:
	    }                                      

	    private void medicamentActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        // TODO add your handling code here:
	    }                                          

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Administrateur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Administrateur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Administrateur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Administrateur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Administrateur1().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton ajouter;
	    private javax.swing.JTextField champsrechercher;
	    private javax.swing.JButton fermer;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTable jTable1;
	    private javax.swing.JLabel labelbienvenu;
	    private javax.swing.JButton lister;
	    private javax.swing.JButton medicament;
	    private javax.swing.JButton modifier;
	    private javax.swing.JButton rechercher;
	    static private Object [][]data;
	    private javax.swing.JTable tableau;
	    static int id_fiche;
	    

		// End of variables declaration                   
		public static int getId_fiche() {
			return id_fiche;
		}

		public static void setId_fiche(int id_fiche) {
			Administrateur1.id_fiche = id_fiche;
		}
		
		public int prendreid(){
			setId_fiche(id_fiche);
			return id_fiche;
		}
		
		
	    // End of variables declaration                   
	
}
