/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mamadou
 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mamadou
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JTextField champlogin = new javax.swing.JTextField();
        JPasswordField champmotdepasse = new javax.swing.JPasswordField();
        JComboBox<Object> liste = new javax.swing.JComboBox<>();
        JButton annuler = new javax.swing.JButton();
        JButton valider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("panel_principale"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        champlogin.setText("Login");
        champlogin.setName("login"); // NOI18N
        getContentPane().add(champlogin);
        champlogin.setBounds(430, 260, 230, 30);

        champmotdepasse.setText("Mot de passe");
        champmotdepasse.setName("motdepasse"); // NOI18N
        champmotdepasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(champmotdepasse);
       champmotdepasse.setBounds(430, 310, 230, 30);

        liste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medecin", "Secretaire", "Administrateur", " " }));
        liste.setName("liste"); // NOI18N
        getContentPane().add(liste);
        liste.setBounds(430, 360, 230, 30);

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/annuler.jpg"))); // NOI18N
        annuler.setText("Annuler");
        annuler.setName("annuler"); // NOI18N
        getContentPane().add(annuler);
        annuler.setBounds(553, 410, 110, 30);

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/ac.jpg"))); // NOI18N
        valider.setText("Valider");
        valider.setName("valider"); // NOI18N
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(430, 410, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/authentification.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 170, 110, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 180, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/medecin.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 960));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 630);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton valider;
    private javax.swing.JButton annuler;
    private javax.swing.JComboBox<String> liste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField champmotdepasse;
    private javax.swing.JTextField champlogin;
    // End of variables declaration                   
}
